import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const testing = api.example.testing.useQuery({ text: 'owowow' })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <SignOutButton>
            <button className="btn">
              Sign Out
            </button>
          </SignOutButton>
          <p className="text-2xl text-white">
            {testing.data ? testing.data.result : 'lwlwowowl'}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
