import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center w-screen h-screen">
        <div className="w-full h-full md:max-w-4xl lg:max-w-5xl xl:max-w-7xl">
          <div className="flex flex-row items-center justify-between gap-4 p-4 h-16 text-lg">
            <div>
              {user.isSignedIn && <UserButton afterSignOutUrl="/"/>}
              {!user.isSignedIn && <SignInButton />}
            </div>


            <div className="flex flex-row justify-between gap-4">
              <div className="font-semibold">Create</div>
              <div>Info</div>
              <div>Recipes</div>
              <div>Ingredients</div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
